### ISSUE TITLE
Screenshots and Sample Code

### ISSUE THREAD

**Issue by thecliguy** [LokiMidgard/NSCI#1]
This looks like a very interesting project. Would it be possible to add some screenshots (animated GIFs would be better) to `README.md` of some interfaces you have made using NSCI?

Also, some sample code would be very useful.

**Comment by LokiMidgard** [comment]
I currently have not so much time working on this :(
But I hope that I will get back to this project in the holidays after christmas. 

Then I will create a better sample project

**Comment by thecliguy** [comment]
Thank you for the quick response. 

OK no problem - I will check back after Christmas.

**Comment by LokiMidgard** [comment]
Just a short status update.

I'm working on Styling, Templating and Binding. As soon this is completed and working I'll start on samples and screenshots. Hope to have something end of next week.

**Comment by thecliguy** [comment]
Happy new year.
Thanks for the update, I will be sure to check back soon.

**Comment by LokiMidgard** [comment]
Well, took longer than anticipated. But I finished the sample project.  
A screen cast should also appear on the root page of this project.
