### ISSUE TITLE
SingelSelectionItemsControl Example

### ISSUE THREAD

**Issue by thecliguy** [LokiMidgard/NSCI#11]
I am having difficulty understanding how to use the control `SingelSelectionItemsControl` correctly. 

Please can you show me a C# example of how to create `SingelSelectionItemsControl` and populate it?

**Comment by LokiMidgard** [comment]
You find a chunk of code in the testharnes project. I also updated it so the items can now be dynamicly added via binding. (also fixed some bugs I found on the way)

https://github.com/LokiMidgard/NSCI/blob/7680955af0b796fbe4e09f6ffeb019063dd9cc09/TestHarness/Program.cs#L82-L131

**Comment by thecliguy** [comment]
Patrick,

A question about the spelling...

"Singel", do you mean "single"? As in only one: http://www.dictionary.com/browse/single
________________________________

**Comment by LokiMidgard** [comment]
Well,... yes.

Spelling has never been my strong suit. 

But I've fixed it now. thank you.

**Comment by LokiMidgard** [comment]
I haven't seen this usecase, But this is most likely whay WPF has Items and Itemssource.

For now the easiset way would be something like this:
```
$Listbox = [NSCI.UI.Controls.SingleSelectionItemsControl]::new()
$Items = [System.Collections.ObjectModel.ObservableCollection<string>]::new()
$Listbox.Items = $Items
$Items.Add("Value 1")
```

In theory The SingleSelectionItemsControl should hear on updates from `INotifyCollectionChanged`. However I heven't testet it that good. Also I'm not sure if the syntax I used to instanciate a generic instance is correct. 

Thats as near as you can come to the desierd function as it is implemented now. But I can't test it currently.

**Comment by thecliguy** [comment]
OK, that all makes sense.

To create the ObservableCollection the PowerShell syntax would be:
`$items = New-Object System.Collections.ObjectModel.ObservableCollection[string]`

I am encountering a problem creating an instance of `SingleSelectionItemsControl`...

In Powershell, instances of a control can be created using two different techniques:

Syntax 1: The `New-Object` cmdlet, EG:
```powershell
$Button = New-Object NSCI.UI.Controls.Button
$Textbox = New-Object NSCI.UI.Controls.TextBox
$Checkbox = New-Object NSCI.UI.Controls.Checkbox
```

Syntax 2: `[Thing]::new()` a static method that attempts to call the constructor(s) with the arguments you supply, EG:
```powershell
$Button = [NSCI.UI.Controls.Button]::new()
$Textbox = [NSCI.UI.Controls.TextBox]::new()
$Checkbox = [NSCI.UI.Controls.Checkbox]::new()
```

Neither of these techniques work against the `SingleSelectionItemsControl`.
`$Listbox = New-Object NSCI.UI.Controls.SingleSelectionItemsControl` and `$Listbox = [NSCI.UI.Controls.SingleSelectionItemsControl]::new()` both result in the following error:
```
Unable to find type [NSCI.UI.Controls.SingleSelectionItemsControl].
At line:1 char:12
+ $Listbox = [NSCI.UI.Controls.SingleSelectionItemsControl]::new()
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (NSCI.UI.Control...ionItemsControl:TypeName) [], RuntimeException
```

**Comment by LokiMidgard** [comment]
I have checked in the corrected name but did not created a new nuget package. Do you use the nuget package to get the lib?

I need to update this.

**Comment by LokiMidgard** [comment]
No, I haven't changed anything in NDProperty sinc two weeks or more. So it should download the latest version. I made some changes (fixes) in NSCI when I testet the sample in TestHarnes. But if you build this project, it should work.

**Comment by thecliguy** [comment]
I am confused why you mentioned nuget? Would an error relating to the instantiation of a control come from NSCI or you think it has something to do with one of the nuget packages?

**Comment by LokiMidgard** [comment]
there is already (preview) nuget package of NSCI on nuget

**Comment by thecliguy** [comment]
Ah OK, I didn't know about that.

So just to clarify, I am just taking the latest source and building it in Visual Studio.

**Comment by LokiMidgard** [comment]
`SingleSelectionItemsControl` is generic. If I understood correctly you need to write

```powershell
$Listbox = New-Object NSCI.UI.Controls.SingleSelectionItemsControl[string]
```

**Comment by thecliguy** [comment]
> SingleSelectionItemsControl is generic. If I understood correctly you need to write

Thank you!! I now have the `SingleSelectionItemsControl` working now in PowerShell.

I have one last problem...

The WPF [ListBox Class](https://msdn.microsoft.com/en-us/library/system.windows.controls.listbox(v=vs.110).aspx) has a property `SelectedIndex`. Can you add this property to `SingleSelectionItemsControl`?

**Comment by thecliguy** [comment]
Regarding my last question, I'm trying to get the index of the selected item. I also tried this but it doesn't seem to work:
```powershell
$Listbox = Listbox.Items.IndexOf($Listbox.SelectedItem)
```

**Comment by LokiMidgard** [comment]
Does `$ListBox.SelectedItem` returns the wrong Value?

**Comment by thecliguy** [comment]
The `SelectedItem` property returns a string which is the value of the selected item.

I would like to be able to get the index of the selected item.

I think there are two ways this could be implemented:
A. Have `SelectedItem` return an object with `value` and `index` properties.
B. Add a new property to the `SingleSelectionItemsControl` for retrieving the index, `SelectedIndex`.

What do you think?

**Comment by LokiMidgard** [comment]
You said that the aproach with indexOf did not work. Through it should be changed so it can be used better using an SelectedIndex Property, it should still work. Maybe you need to call IndexOf on `$Items` instead of `$ListBox.Items`. Last one was an `IEnumerable`, `IndexOf` Is a member of `IList`. If I remember correctly.

I have created an issue for getting the selected index. I think it is realy missing. I'm not sure if I shuld return an object that holds bothe, or a tuple. This could make problems using the binding mechanic as it is implemented now.

I'm not sure when I get to implement this. The next two weekends are already planed.

**Comment by thecliguy** [comment]
> You said that the aproach with indexOf did not work.

Sorry, I was wrong. This does work:
```powershell
$Listbox.Items.IndexOf($Listbox.SelectedItem)
```

Can `SelectedItem` be used to set the selected item? EG can I use it to make `D` in the example below the selected item?
![image](https://user-images.githubusercontent.com/23440389/41407664-0489bc3e-6fc8-11e8-861c-d2e2bb1e284e.png)

**Comment by thecliguy** [comment]
Patrick - Don't worry about my last question. I have resolved it now.

The only outstanding thing is adding a `SelectedIndex` property to Item Controls, I see you have created issue #12 for this.

So shall I close this issue now, as all questions have now been answered?



#11 (comment)

**Comment by LokiMidgard** [comment]
If all questions have been resolve. I close it ^^

You can always open a new one (or this) if there are other problems or questions.

**Comment by thecliguy** [comment]
Thanks for your time and patience, much appreciated.
