### ISSUE TITLE
Compiling in Visual Studio 2017 on Windows 10

### ISSUE THREAD

**Issue by thecliguy** [LokiMidgard/NSCI#2]
Compiling in Visual Studio 2017 on Windows 10 fails with the following errors:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "GenerateCodeFromAttributes" task failed unexpectedly.
System.ArgumentException: Object type cannot be converted to target type.
   at CodeGeneration.Roslyn.Tasks.Helper.set_Compile(ITaskItem[] value)
   at CodeGeneration.Roslyn.Tasks.GenerateCodeFromAttributes.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	NSCI	C:\Users\thecliguy\.nuget\packages\codegeneration.roslyn.buildtime\0.3.9\build\CodeGeneration.Roslyn.BuildTime.targets	20	

Error	MSB4018	The "GenerateCodeFromAttributes" task failed unexpectedly.
System.ArgumentException: Object type cannot be converted to target type.
   at CodeGeneration.Roslyn.Tasks.Helper.set_Compile(ITaskItem[] value)
   at CodeGeneration.Roslyn.Tasks.GenerateCodeFromAttributes.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	NSCI.Sample	C:\Users\thecliguy\.nuget\packages\codegeneration.roslyn.buildtime\0.3.9\build\CodeGeneration.Roslyn.BuildTime.targets	20	

Error	MSB4018	The "GenerateCodeFromAttributes" task failed unexpectedly.
System.ArgumentException: Object type cannot be converted to target type.
   at CodeGeneration.Roslyn.Tasks.Helper.set_Compile(ITaskItem[] value)
   at CodeGeneration.Roslyn.Tasks.GenerateCodeFromAttributes.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	NSCI.Sample	C:\Users\thecliguy\.nuget\packages\codegeneration.roslyn.buildtime\0.3.9\build\CodeGeneration.Roslyn.BuildTime.targets	20	

Error	MSB4018	The "GenerateCodeFromAttributes" task failed unexpectedly.
System.ArgumentException: Object type cannot be converted to target type.
   at CodeGeneration.Roslyn.Tasks.Helper.set_Compile(ITaskItem[] value)
   at CodeGeneration.Roslyn.Tasks.GenerateCodeFromAttributes.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	TestHarness	C:\Users\thecliguy\.nuget\packages\codegeneration.roslyn.buildtime\0.3.9\build\CodeGeneration.Roslyn.BuildTime.targets	20	

Error	MSB4018	The "GenerateCodeFromAttributes" task failed unexpectedly.
System.ArgumentException: Object type cannot be converted to target type.
   at CodeGeneration.Roslyn.Tasks.Helper.set_Compile(ITaskItem[] value)
   at CodeGeneration.Roslyn.Tasks.GenerateCodeFromAttributes.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	TestHarness	C:\Users\thecliguy\.nuget\packages\codegeneration.roslyn.buildtime\0.3.9\build\CodeGeneration.Roslyn.BuildTime.targets	20	
```

Are there any prerequisites which need to be satisfied in order to compile?

**Comment by LokiMidgard** [comment]
Every prerequest should be included using Nuget. I also build it under Windows 10 and Visual studio 2017 (Comunity). I'm a little outdated  what the `CodeGeneration.Roslyn` dependency maybe ther is a problem. 

Can you build [NDProperty](https://github.com/LokiMidgard/NDProperty)?

I'll try to build it on another PC maybe then I can reproduce it.

**Comment by LokiMidgard** [comment]
I was able to reproduce this on another machine.

Maybe one of the dependencys will get resolved to a newer version.

When I get home I will check against what versions of those I have in my project.
```
codegeneration.roslyn.attributes~0.3.9
codegeneration.roslyn.buildtime~0.3.9
ndproperty~0.13.7
ndproperty.analyzer~0.13.7
ndproperty.core~0.13.7
ndproperty.generator~0.13.7
ndproperty.generator.attributes~0.13.7
nito.asyncex.context~5.0.0-pre-03
nito.asyncex.tasks~5.0.0-pre-03
nito.disposables~1.2.1
runtime.any.system.collections~4.3.0
runtime.any.system.diagnostics.tools~4.3.0
runtime.any.system.diagnostics.tracing~4.3.0
runtime.any.system.globalization~4.3.0
runtime.any.system.globalization.calendars~4.3.0
runtime.any.system.io~4.3.0
runtime.any.system.reflection~4.3.0
runtime.any.system.reflection.extensions~4.3.0
runtime.any.system.reflection.primitives~4.3.0
runtime.any.system.resources.resourcemanager~4.3.0
runtime.any.system.runtime~4.3.0
runtime.any.system.runtime.handles~4.3.0
runtime.any.system.runtime.interopservices~4.3.0
runtime.any.system.text.encoding~4.3.0
runtime.any.system.text.encoding.extensions~4.3.0
runtime.any.system.threading.tasks~4.3.0
runtime.any.system.threading.timer~4.3.0
runtime.win-x86.microsoft.netcore.app~2.0.0
runtime.win-x86.microsoft.netcore.dotnetapphost~2.0.0
runtime.win-x86.microsoft.netcore.dotnethostpolicy~2.0.0
runtime.win-x86.microsoft.netcore.dotnethostresolver~2.0.0
runtime.win.microsoft.win32.primitives~4.3.0
runtime.win.system.console~4.3.0
runtime.win.system.diagnostics.debug~4.3.0
runtime.win.system.io.filesystem~4.3.0
runtime.win.system.net.primitives~4.3.0
runtime.win.system.net.sockets~4.3.0
runtime.win.system.runtime.extensions~4.3.0
runtime.win7-x86.runtime.native.system.io.compression~4.3.0
runtime.win7.system.private.uri~4.3.0
system.private.uri~4.3.0
system.reflection.typeextensions~4.4.0
system.threading.overlapped~4.3.0
system.valuetuple~4.3.1
system.xml.xmlserializer~4.3.0
```

I also should update the dependencys to `codegeneration.roslyn` but lust time I checked you needed to add an aditional nuget feed to use it (~_ ~;)

It seems I also had the problem [before](https://github.com/AArnott/CodeGeneration.Roslyn/issues/12) but I thought I managed to get it to run using a clean and rebuild. But this time it didn't work.

**Comment by thecliguy** [comment]
Thanks for looking into this.

OK, I won't take any action - I will wait for an update from you.

**Comment by LokiMidgard** [comment]
hm...

The depandencys are exactly the same. I cleard all local nuget packages and reinstalled them. Cloned a new reposetory of this project and everything worked fine. I'll won't have access to the failing machine untill sometime next week, so this could take some time.

Unless I can brake my dev machine of course.

Neverless I'll try something.

**Comment by LokiMidgard** [comment]
One difference I found was that on my test machine where it failed I was missing .Net Framework 7.6.2. I couldn't compile projects that were targeting 7.6.2. The generator is compiled with 7.6.2. But I assume if you use windows 10 with current Visual Studio it will be present. So this is likely not the problem.

**Comment by thecliguy** [comment]
Sorry, I didn't understand your explanation of the .Net version numbers.

Current versions of .Net framework are 4._x_._x_ - but you refer to 7._x_._x_ ??

**Comment by LokiMidgard** [comment]
Yeah sorry, I mean 4.6.2 not 7.6.2. But as mentioned I don't think that this is the problem. I still try to find out what the deiference is. And for now there are 3 differences between my working system and the not working one.

Not Workgin
* Support Target framework `.Net Framework 4.6.1`
* Windows 7
* Visual Studio 2017 Enterprise

Working:
* Support Target framework `.Net Framework 4.6.2`
* Windows 10
* Visual Studio 2017 Community

However you are also working on Windows 10 so point two is invalid. And the other two also seem to be unlikly.

**Comment by thecliguy** [comment]
My laptop is running the following: 
- Visual Studio Community 2017, Version 15.5.7
- .NET Framework, Version 4.7.1
- Windows 10 Pro, Version: 1709 10.0.16299.192

**Comment by LokiMidgard** [comment]
I haven't get further in finding out what the difference actually could be besides the `.Net Framework` version. But I hope that updating the dependency `CodeGeneration.Roslyn` to a newer version will help.

Unfortunatly the new version breaks another part of the code generator of NDProperty.

Following [pull request](https://github.com/AArnott/CodeGeneration.Roslyn/pull/62) should fix the problem. So resolution of this issue will be blocked by it.

But I will try if the potential fix will resolve this issue hopefully at thuseday or wednesdey. If following [Branch](https://github.com/LokiMidgard/NDProperty/tree/TestGeneratorBuild) of NDProperty builds but the master branch does not, it should fix this issue.

To build the branch the version of `CodeGeneration.Roslyn` must be the version build from the branch which can be found [here](https://ci.appveyor.com/project/AArnott/codegeneration-roslyn/build/0.4.26+gc7537ced7c/artifacts). The automated build sets the version of the dependencys wrong (its `1.0.0` instead of `0.4.26+gc7537ced7c`). When using those the nuget packages must be edited. Otherwise one can download [following packages](https://kranz-my.sharepoint.de/:u:/g/personal/patrick_kranz_onmicrosoft_de/ETAsqtOTzTZPsSoJFjASGVkB0kEBhrSf8zUgQ5D6JhgR7g?e=XJYN50). Those have already been edited.

**Comment by LokiMidgard** [comment]
I tested this version, but it didn't worked. I unable to work ob this week, so it will take some time until I can investigate further, Sorry for the delay.

**Comment by thecliguy** [comment]
@LokiMidgard I see the PR was accepted. I guess you are just waiting now for AArnott to make a release?

**Comment by thecliguy** [comment]
Ah OK, I assumed [PR #62](https://github.com/AArnott/CodeGeneration.Roslyn/pull/62) didn't make it into 0.4.42 because the release notes just say:
```
Merge pull request #70 from amis92/fix/commandline-inlining
Inline System.CommandLine into Tool project, closes pull request s
```

**Comment by LokiMidgard** [comment]
No sorry, I'm the bottlenek.

**Comment by AArnott** [comment]
@thecliguy Sorry. Those release notes were written by appveyor and only convey the message from the last commit that went in.

**Comment by LokiMidgard** [comment]
Just a short update. I currently a little short on time. Sorry that I can't get it fixed for so long. I hope I can get time at the long weekend.

**Comment by LokiMidgard** [comment]
The new version should now work. But I haven't test it on the machine where it failed for me yet. It can be some days until I can test it on this machine.

**Comment by LokiMidgard** [comment]
I could test it today. It worked on the machine where it previosly faild. Unfortunatly I still don't know why it faild on some machines and did work on others.

For now I will close this issue. If this will still not work, please comment.

**Comment by thecliguy** [comment]
@LokiMidgard - I tested today and the solution now builds. :thumbsup: 

In the screenshot on the `README.md` it shows the sample application is an executable (the titlebar contains `NSCI.exe`).

So at first I was confused why the build did not generate an EXE. But I think I understand now, because it is targeting .Net Core it produces a DLL, not an EXE. To run the sample app you need to call `dotnet.exe` and pass the DLL as an argument, EG: 
`dotnet.exe NSCI-master\NSCI.Sample\bin\Debug\netcoreapp2.0\NSCI.Sample.dll`

I think the screenshot must have been built against .Net 4.6, not .Net Core.

Maybe its a good idea to add some documentation explaining how to run the sample application - and perhaps update the screenshot too? What do you think?
