### ISSUE TITLE
CanReject is False. Setting MutatedValue is not allowed

### ISSUE THREAD

**Issue by viteo** [LokiMidgard/NSCI#3]
Hi! Thank you for fixing #2. Can't wait to try it, but...
When I start NSCI.Sample project it fails with 

> 'System.InvalidOperationException' occurred in NDProperty.Core.dll
> CanReject is False. Setting MutatedValue is not allowed'

at TextBlock.cs:15

`arg.Provider.MutatedValue = arg.Provider.NewValue?.Replace("\t", "    ").Replace("\r", "");`

Also, have to mention that I'm getting two warnings:
> warning NU1701: Package 'Microsoft.Composition 1.0.27' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. 

and

> Warning IDE1003: Analyzer assembly c:\Users\\.nuget\packages\ndproperty.analyzer\0.13.11\analyzers\dotnet\cs\CodeGeneration.Roslyn.dll' depends on 'Microsoft.Extensions.DependencyModel, Version=2.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' but it was not found. Analyzers may not run correctly unless the missing assembly is added as an analyzer reference as well.

**Comment by LokiMidgard** [comment]
The exception should no longer apear.

For those Warnings, I think I need to switch to a .net standard implementation of the Analizer. I will then also look after the missing Assembly.
