### ISSUE TITLE
Something with charset/code table/system locale

### ISSUE THREAD

**Issue by viteo** [LokiMidgard/NSCI#4]
On my work computer i have Windows 7 in English, but with Russian system locale for non-unicode programs installed.
![3](https://user-images.githubusercontent.com/9247937/40474718-6d08e964-5f48-11e8-818d-70c7effad737.PNG)
and the Sample program looks like:
![1](https://user-images.githubusercontent.com/9247937/40474839-b2aba786-5f48-11e8-809a-2333ec3e251c.PNG)
![2](https://user-images.githubusercontent.com/9247937/40474843-b486e48a-5f48-11e8-92f8-cec4ecd6e723.PNG)
I've changed system locale to English (US), but the result has not changed a lot (still something is wrong with character set)
![4](https://user-images.githubusercontent.com/9247937/40474958-f8383f62-5f48-11e8-9446-c7e62d18527e.PNG)
I've tried to manually set CultureInfo at the beginnig of Main(), but the result is still the same
`System.Threading.Thread.CurrentThread.CurrentCulture = CultureInfo.GetCultureInfo("en-US");
System.Threading.Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo("en-US");`

**Comment by thecliguy** [comment]
Please don't consider this "the answer", its just a thought...

My understanding is that the standard ASCII character range is 128 (0–127). When working with characters outside this range, the choice of code page determines the set of characters displayed.

Windows ships with a console tool `C:\windows\System32\chcp.com` for getting and setting the code page. My code page is set to 437, the table on [this page](https://ss64.com/nt/chcp.html) indicates that 437 is `United States`.

Can you check your code page?

**Comment by LokiMidgard** [comment]
I checked with my current machine there it is 437 (an english os). Everything shows as expected. I will also check a machine with german os where I know that it runns without problems. However this system has a Windows 10.

Actually those [two lines](https://github.com/LokiMidgard/NSCI/blob/a4a96cbf4f2d3600accf7a34ed6fec898d5a261b/NSCI/UI/RootWindow.cs#L116-L117) should enable UTF-8 support. without it I also had some problems with some characters. But maybe I missunderstood thos calls.

What font your console uses? I also expirenced that some fonts supported mor diferent line/block characters. I have on the english system `Lucida Console`.

**Comment by viteo** [comment]
It is also 437 codepage. In the settings it is "Raster Fonts", i've changed it to Lucida Console and now it works. Thank you guys.
![5](https://user-images.githubusercontent.com/9247937/40490063-50c57f62-5f73-11e8-9edd-880a358a6a19.PNG)
![6](https://user-images.githubusercontent.com/9247937/40490075-581fa8b4-5f73-11e8-9b56-ac1a3165b8d5.PNG)

**Comment by LokiMidgard** [comment]
it would be nice to get the fonts for the console, or better to set them, but I'm not aware of any api that can do this.

**Comment by thecliguy** [comment]
@LokiMidgard Last year I looked for a solution to programmatically set the console font. I found this to be useful, see the answer from user **Nation_State_Tractor**: [Change the console font programmatically](https://www.reddit.com/r/PowerShell/comments/4q8bkm/change_the_console_font_programmatically).

Additionally, I have used a command line tool `Setconsole.exe`, see http://prozandcoms.stefanoz.com
To change the font to 'Lucida Console': `setconsole.exe /f:lucida`
