### ISSUE TITLE
SIGINT (Exiting RootWindow's Run Method)

### ISSUE THREAD

**Issue by thecliguy** [LokiMidgard/NSCI#8]
Conventionally, console applications respond to CTRL+C as a `SIGINT` signal and not as keyboard input.

`SIGINT` can be intercepted by an application so that it can perform a clean exit.

Windows doesn't have many examples of interactive console applications, but one example is the text editor Vim. Upon intercepting a `SIGINT` Vim prompts the user to exit the program by using its quit syntax: 
![image](https://user-images.githubusercontent.com/23440389/40689373-bef5a53c-6399-11e8-8b4b-20c9d08c2706.png)

On Linux, there are many examples of console applications which respond to `SIGINT`, such as:
  * htop _(interactive process viewer)_
  * Mutt _(email client)_
  * Lynx _(text web browser)_
  * GoAccess _(web log analyzer)_

Ideally NSCI would give the programmer the option to simply ignore `SIGINT` or to take some action.

**Comment by LokiMidgard** [comment]
I have added an options parameter to the `RootWindow` constructor that controls this.

**Comment by thecliguy** [comment]
@LokiMidgard Using the latest commit, I get the following error on the Run method of `RootWindow`:
```
Exception calling "Run" with "0" argument(s): "This property has already been set and cannot be modified."
```

**Comment by LokiMidgard** [comment]
I've added this line
https://github.com/LokiMidgard/NSCI/blob/9361d5fc777a4bd82880b3e6180e9f65ed969346/NSCI/UI/RootWindow.cs#L179

In my tests this runs without problems, are you setting a Thread name somewhere explicit?

**Comment by LokiMidgard** [comment]
Hm...  
in PowerShell the thread is already named `Pipeline Execution Thread`. Hope that this does make more problems.

**Comment by thecliguy** [comment]
That has fixed the error, but I cannot get <kbd>ctrl</kbd> + <kbd>c</kbd> to work in PowerShell.

I have implemented the following, but when pressing <kbd>ctrl</kbd> + <kbd>c</kbd> nothing happens:
```powershell
$NsciOptions = [NSCI.UI.NsciOptions]::new()
$NsciOptions.TreatControlCAsInput = $False
$Root = [NSCI.UI.RootWindow]::new($NsciOptions)
```

It works fine for me in C# though:
```c#
var NsciOptions = new NSCI.UI.NsciOptions
{
    TreatControlCAsInput = false
};

var root = new NSCI.UI.RootWindow(NsciOptions);
var grid = new Grid();
```

Any ideas? Does it work in PowerShell for you?

**Comment by LokiMidgard** [comment]
Unfrotunatly I have no idea. The `CanleKeyPress` call back is used, but it does not matter if `ConsloeCancelEventArgs.Cancel` is false or true. the console application does not stop.

I'm not sure whit the scripting stuff, maybe ctrl-c would terminate the process, but there was no process started. So only the executed function is terminated, but not additional threads that were spawned like UI and input thread.  If that would be the case, then you would need to handle OnCancelPressed yourself and call Detach on the RootWindow.

**Comment by LokiMidgard** [comment]
I've noticed wired behavior when the application was terminated via `esc` input behaves strage after that.

Most likely the input thread was still running. It was actually an endless loop, that was intended to live as long as the process. And when the process was killed it should vanish. But this did not happen in PowerShell.

I no explicitly stop the Thread if the app was stoped like the UI thread before. However The thread is most likely currently blocking in `Console.ReadKey()` when the app is stoped. And thus the first key pressed after termination will be consumed.

So, for PowerShell you must handle the Ctrl+C command with a Detach yourself.

**Comment by thecliguy** [comment]
@LokiMidgard OK, I have handled <kbd>ctrl</kbd> + <kbd>c</kbd> by assigning a [ScriptBlock](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_script_blocks?view=powershell-6) to `OnCancelPressed` which calls the `Detach` method of the `RootWindow`:
```powershell
$NsciOptions = [NSCI.UI.NsciOptions]::new()
$NsciOptions.TreatControlCAsInput = $False
$NsciOptions.OnCancelPressed = {$Root.Detach()}
$Root = [NSCI.UI.RootWindow]::new($NsciOptions)
```

<kbd>ctrl</kbd> + <kbd>c</kbd> now exits the script but there are two problems...

**Problem 1:**
After exiting, you must now press a key twice before it is displayed on the console window. EG, if you want to type the letter `A`, you must press the `A` key twice.

**Problem 2:**
When NSCI exits it clears the console buffer. This is not the expected behaviour for a console application. When a console application exits, any output present on the console prior to it starting should be preserved when it exits. Try any console application on Linux and you will see this is the standard behaviour (EG. vim, htop, Mutt, etc).

**Possible solution:**
There are two types of screen buffer - the `Normal Screen Buffer` and the `Alternate Screen Buffer`. This is a standard found in almost all consoles/terminals, so it should work in almost any console on any operating system. When a full screen console application is invoked, it should use the `Alternate Screen Buffer`. When the application exits the console will return to the `Normal Screen Buffer`. So NSCI should be using the `Alternate Screen Buffer`.

Here is some information on the `Alternate Screen Buffer`:
  * [Thomas Dickey - The Alternate Screen Buffer](http://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-The-Alternate-Screen-Buffer)
  * [Microsoft - Console Virtual Terminal Sequences](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#span-idalternatescreenbufferspanspan-idalternatescreenbufferspanspan-idalternatescreenbufferspanalternate-screen-buffer)

If NSCI used the `Alternate Screen Buffer` it should fix **problem 2** and it _might_ also fix **problem 1**.

I can do some more research into implementing `Alternate Screen Buffer` in a C# application. I would be interested in your thoughts...

**Comment by thecliguy** [comment]
@LokiMidgard Your commit to terminate input thread when application stops (https://github.com/LokiMidgard/NSCI/commit/48336a47a430eea6ee6feea4b7c361143adccea6) has fixed **problem 1** in my last comment.

**Comment by LokiMidgard** [comment]
If this would work, it would be nice. But as far as I know the C# `Console` class is quite limited. I haven't found any method to switch to an alternative screen buffer. Also escape sequences to manipulate the console don't work. (e.g. `"\x1b[31mThis text has a red foreground using SGR.31.\r\n"`)

I have disabled `Console.Clear()` as you suggested.

**Comment by LokiMidgard** [comment]
> @LokiMidgard Your commit to terminate input thread when application stops (48336a4) has fixed problem 1 in my last comment.

I still have this problem for the first charakter I type after termination. Maybe I need to operate on the inputstream directly instead of using the `Console.ReadKey()` method. I need to check this out another time.

**Comment by thecliguy** [comment]
Sorry, I don't think the changes in https://github.com/LokiMidgard/NSCI/commit/f62db0e6f8bd3d3daefd244a73c4fb55e7b540ad are a good idea.

I think its better to revert those changes and implement `Alternate Screen Buffer` instead.

VT escape sequence support has existed in *nix forever. In Windows, it was introduced into conhost in the Windows 10 Anniversary Update: https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences

The reason the VT escape sequence was not working for you is because you have to explicitly enable Virtual Terminal Processing in NSCI for the Windows console.

Please see this example: https://github.com/thecliguy/NSCI/commit/d21d3924082460312c993b584d7406294a7aa08b, where I have 
  * Added support for Virtual Terminal Processing.
  * Enable `Alternate Screen Buffer` when `RootWindow` is run.
  * Enable `Normal Screen Buffer` when `RootWindow` is exited.

It is not the best code because I am not a C# developer.

There is one problem with the code, colours do not work:
![image](https://user-images.githubusercontent.com/23440389/41824158-a7b34c66-7803-11e8-8a7d-2580d6e85279.png)

**Comment by thecliguy** [comment]
I forgot to remove the changes from this commit in my code: https://github.com/LokiMidgard/NSCI/commit/f62db0e6f8bd3d3daefd244a73c4fb55e7b540ad

Its better they are removed.

**Comment by LokiMidgard** [comment]
Up to now I explicitly tried to avoid native code and have a .net only implementation.
I inteded it to run also on Linux and mac. But this extern methods are only used on Windows and Linux should support thos code without any setting.

The next thing that comes in mind is what happens on Systems previor to Windows 10 Anniversary Update. 

I still would like to use the alternate screenbuffer, currently I have some problems with the line break of the last char and I hope the alternate screen buffer could prevent this.

By the way, thanks for your implementation. I will look at it in the next days.

**Comment by LokiMidgard** [comment]
If you don't mind we can continue this in #16.
