### ISSUE TITLE
Unfork NSCI from CLRCLI

### ISSUE THREAD

**Issue by thecliguy** [LokiMidgard/NSCI#9]
Since NSCI and CLRCLI do not share any code (they are just conceptually similar), please consider unforking from CLRCLI.

Currently you cannot search the project's codebase from Github because it is a fork:
![image](https://user-images.githubusercontent.com/23440389/40690027-e62de0f8-639c-11e8-8f0a-9b5b1c45b74a.png)

I don't think that the Github interface has any facility to unfork, so you need to contact Github support with a request.

I think its a good idea to get this done now before more people start discovering the project.

**Comment by LokiMidgard** [comment]
So this should no longer be a fork. And your Fork of this repository should still be attached to it.
